# Hexo 配置
## 文档: https://hexo.io/docs/configuration.html
## 源代码: https://github.com/hexojs/hexo/

# 站点信息
title: Hexo #网站标题
subtitle: 'sub title' #网站副标题
description: 'description' #网站描述description 主要用于SEO，告诉搜索引擎一个关于您站点的简单描述，通常建议在其中包含您网站的关键词。
keywords: ['code','java'] #网站的关键词。支持多个关键词。
author: 'Inyxin' #作者名字, 参数用于主题显示文章的作者。
language: 'en' #网站使用的语言。对于简体中文用户来说，使用不同的主题可能需要设置成不同的值，请参考你的主题的文档自行设置，常见的有en, zh-Hans和 zh-CN。
timezone: 'Asia/Shanghai'

# 网址设置
## 在此处设置你的站点 URL。例如，如果你使用 GitHub Pages，请将 URL 设置为 'https://username.github.io/project'
url: https://inyxin.github.io #网址, 必须以 http:// 或 https:// 开头
permalink: post/:hash/
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: true # 将 'index.html' 添加到永久链接时设为 false 可移除尾随的 'index.html'
  trailing_html: true # 将 '.html' 添加到永久链接时设为 false 可移除尾随的 '.html'

# 目录设置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作设置
new_post_name: :title.md # 新文章的文件名格式
default_layout: post
titlecase: false # 将标题转换为标题案例
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site # 应用于整个站点
  exclude: ''
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #显示草稿
post_asset_folder: true #启用 资源文件夹
relative_link: true #把链接改为与根目录的相对位址
future: true #显示未来的文章
#代码块的设置, 请参考 代码高亮 进行设置
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''


# 主页设置
# path: 博客首页的根路径。（默认 = ''）
# per_page: 每页显示的文章数量。（0 = 禁用分页）
# order_by: 文章排序方式。（默认按日期降序）
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类与标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期 / 时间格式
## Hexo 使用 Moment.js 解析和显示日期
## 可以按照 http://momentjs.com/docs/#/displaying/format/ 中定义的格式自定义日期格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option 支持 'mtime', 'date', 'empty'
updated_option: mtime

# 分页设置
## 将 per_page 设置为 0 禁用分页
per_page: 10
pagination_dir: page

# 包含 / 排除文件
## include:/exclude: 选项仅适用于 'source/' 文件夹
include:
exclude:
ignore:

# 扩展
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/
theme: cactus
# 部署
## 文档: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:INYXIN/inyxin.github.io.git
    branch: blog
  - type: git
    repo: git@gitee.com:INYXIN/INYXIN.git
    branch: blog

# 文章归档设置
archive_generator:
  #per_page: 0 指定文章归档页面的条目数，0 为无限制。
  per_page: 0  
  yearly: false
  monthly: false
  daily: false
